import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const rootEnvPath = resolve(rootDir, ".env");
const iosLocalXcconfig = resolve(rootDir, "ios-app/Config/Local.xcconfig");

/** Parse KEY=VALUE lines from a dotenv file (no expansion). */
export function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return {};
  const out = {};
  for (const raw of readFileSync(filePath, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

export function loadRootEnv() {
  return parseEnvFile(rootEnvPath);
}

/** Trimmed LAN IP from root `.env`, or empty string when unset. */
export function getLanLocalIpAddress(env = loadRootEnv()) {
  return (env.LAN_LOCAL_IP_ADDRESS ?? process.env.LAN_LOCAL_IP_ADDRESS ?? "").trim();
}

/** xcconfig treats `//` as a comment — use `http:/$()/host` for URLs. */
function xcconfigHttpUrl(url) {
  return url.replace(/^https?:\/\//, (scheme) => `${scheme.slice(0, -2)}/$()/`);
}

/**
 * Write/remove iOS Local.xcconfig and return env overrides for Node processes.
 * When LAN is set: API media URLs + iOS base URL use that IP; callers should bind web to 0.0.0.0.
 */
export function applyLanSideEffects(lan = getLanLocalIpAddress()) {
  mkdirSync(dirname(iosLocalXcconfig), { recursive: true });

  const overrides = {};
  if (lan) {
    const apiBase = `http://${lan}:3000`;
    writeFileSync(
      iosLocalXcconfig,
      `// Generated by scripts/lan.mjs from root .env LAN_LOCAL_IP_ADDRESS — do not edit.\n` +
        `GOBID_API_BASE_URL = ${xcconfigHttpUrl(apiBase)}\n`,
      "utf8",
    );
    overrides.LAN_LOCAL_IP_ADDRESS = lan;
    overrides.API_PUBLIC_URL = apiBase;
    overrides.NEXT_PUBLIC_SITE_URL = `http://${lan}:3002`;
    overrides.NEXT_PUBLIC_API_URL = apiBase;
    console.log(`[lan] LAN_LOCAL_IP_ADDRESS=${lan}`);
    console.log(`[lan] web → http://${lan}:3002  |  iOS/API → ${apiBase}`);
  } else if (existsSync(iosLocalXcconfig)) {
    unlinkSync(iosLocalXcconfig);
    console.log("[lan] LAN_LOCAL_IP_ADDRESS empty — localhost only (iOS → 127.0.0.1:3000)");
  }

  return overrides;
}

export { rootDir };
